#!/usr/bin/env python3
"""Mirror tokens/tokens.css to tokens/tokens.json.

tokens.css is the single source of truth. This script never writes CSS.
Run after any token change:

    python3 tokens/sync-tokens.py          # rewrite tokens.json
    python3 tokens/sync-tokens.py --check  # exit 1 if tokens.json is stale

The provenance tag in each declaration's trailing comment is carried through to
the JSON as `source`, so a token's origin survives the hop between formats.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CSS = ROOT / "tokens.css"
JSON_OUT = ROOT / "tokens.json"

DECL = re.compile(
    r"^\s*(--es-[a-z0-9-]+)\s*:\s*([^;]+);\s*(?:/\*\s*(.*?)\s*\*/)?\s*$"
)
SELECTOR = re.compile(r"^\s*([^{@/][^{]*?)\s*\{\s*$")
PROVENANCE = re.compile(r"\[(theme|svg|xml|pdf|sampled|measured|INFERRED)\]")

# --es-<group>-<name>; these two-word groups are kept intact.
COMPOUND = ("colour-surface", "colour-text", "colour-border", "colour-evidence",
            "colour-data", "colour-scale", "colour-ramp", "colour-status",
            "motion-duration", "motion-ease")


def group_of(name: str) -> tuple[str, str]:
    body = name[len("--es-"):]
    for prefix in COMPOUND:
        if body.startswith(prefix + "-"):
            return prefix, body[len(prefix) + 1:]
    head, _, tail = body.partition("-")
    return head, tail or head


def parse(css: str) -> dict:
    scopes: dict[str, dict] = {}
    current = None
    at_rule = None
    for line in css.splitlines():
        stripped = line.strip()
        if stripped.startswith("@") and stripped.endswith("{"):
            at_rule = stripped[:-1].strip()
            continue
        sel = SELECTOR.match(line)
        if sel:
            # A :root inside an at-rule is a different scope, not a redefinition
            # of the base one — otherwise the reduced-motion block would silently
            # overwrite the real motion tokens.
            current = sel.group(1).strip()
            if at_rule:
                current = f"{at_rule} {{ {current} }}"
            scopes.setdefault(current, {})
            continue
        if stripped.startswith("}"):
            if current is None:
                at_rule = None
            current = None
            continue
        decl = DECL.match(line)
        if not decl or current is None:
            continue
        name, value, comment = decl.group(1), decl.group(2).strip(), decl.group(3) or ""
        tags = PROVENANCE.findall(comment)
        group, key = group_of(name)
        scopes[current].setdefault(group, {})[key] = {
            "var": name,
            "value": value,
            "source": tags[0] if tags else "derived",
            "note": PROVENANCE.sub("", comment).strip(" —-") or None,
        }
    return {k: v for k, v in scopes.items() if v}


def build() -> dict:
    scopes = parse(CSS.read_text(encoding="utf-8"))
    root = scopes.pop(":root", {})
    return {
        "$schema": "https://design-tokens.org/community-group",
        "name": "Essential Research",
        "description": (
            "Design tokens for Essential Research. Extracted from the brand asset "
            "pack and the NLA and Oxfam reference reports. tokens.css is the source "
            "of truth; this file is generated by tokens/sync-tokens.py."
        ),
        "provenance": {
            "theme": "ppt/theme/theme1.xml, clrScheme 'Custom 6' and fontScheme",
            "svg": "ER/Screen/EPS/Secondary Research Logo *.svg",
            "xml": "slide-level XML in the Oxfam .pptx",
            "pdf": "font table of the NLA native PDF",
            "sampled": "pixel-sampled from a flat fill in reference/renders/",
            "measured": "geometry measured from a render, normalised to 1280x720",
            "INFERRED": "not present in any source asset — derived, basis stated in the note",
        },
        "tokens": root,
        "scopes": scopes,
    }


def main() -> int:
    payload = json.dumps(build(), indent=2, ensure_ascii=False) + "\n"
    if "--check" in sys.argv:
        current = JSON_OUT.read_text(encoding="utf-8") if JSON_OUT.exists() else ""
        if current != payload:
            print("tokens.json is out of date — run: python3 tokens/sync-tokens.py")
            return 1
        print("tokens.json is in sync with tokens.css")
        return 0
    JSON_OUT.write_text(payload, encoding="utf-8")
    counts = build()["tokens"]
    total = sum(len(v) for v in counts.values())
    print(f"wrote {JSON_OUT.relative_to(ROOT.parent)} — {total} tokens in {len(counts)} groups")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
